export interface Country {
  code: string;
  name: string;
  currency: string;
  timezone: string;
  flag: string;
  currencySymbol: string;
}

/** Returns flag emoji for an ISO 3166-1 alpha-2 country code (e.g. "US" → 🇺🇸). */
export function getFlagEmoji(code: string): string {
  if (code.length !== 2) return ""
  const a = 0x1f1e6 - 65 + code.toUpperCase().charCodeAt(0)
  const b = 0x1f1e6 - 65 + code.toUpperCase().charCodeAt(1)
  return String.fromCodePoint(a, b)
}

/** Currency code to symbol map (ISO 4217). Falls back to code if not listed. */
export const CURRENCY_SYMBOLS: Record<string, string> = {
  AFN: "؋", ALL: "L", AMD: "֏", ANG: "ƒ", AOA: "Kz", ARS: "$", AUD: "A$", AWG: "ƒ", AZN: "₼",
  BAM: "KM", BBD: "$", BDT: "৳", BGN: "лв", BHD: ".د.ب", BIF: "FBu", BMD: "$", BND: "$", BOB: "Bs",
  BRL: "R$", BSD: "$", BTN: "Nu.", BWP: "P", BYN: "Br", BZD: "BZ$", CAD: "C$", CDF: "FC", CHF: "CHF",
  CLP: "$", CNY: "¥", COP: "$", CRC: "₡", CUP: "₱", CVE: "$", CZK: "Kč", DJF: "Fdj", DKK: "kr",
  DOP: "RD$", DZD: "د.ج", EGP: "E£", ERN: "Nfk", ETB: "Br", EUR: "€", FJD: "$", FKP: "£", GBP: "£",
  GEL: "₾", GHS: "₵", GIP: "£", GMD: "D", GNF: "FG", GTQ: "Q", GYD: "$", HKD: "HK$", HNL: "L",
  HRK: "kn", HTG: "G", HUF: "Ft", IDR: "Rp", ILS: "₪", INR: "₹", IQD: "ع.د", IRR: "﷼", ISK: "kr",
  JMD: "J$", JOD: "د.ا", JPY: "¥", KES: "KSh", KGS: "с", KHR: "៛", KMF: "CF", KPW: "₩", KRW: "₩",
  KWD: "د.ك", KZT: "₸", LAK: "₭", LBP: "ل.ل", LKR: "Rs", LRD: "$", LSL: "L", LYD: "ل.د", MAD: "د.م.",
  MDL: "L", MGA: "Ar", MKD: "ден", MMK: "K", MNT: "₮", MOP: "MOP$", MRU: "UM", MUR: "₨", MVR: "Rf",
  MWK: "MK", MXN: "Mex$", MYR: "RM", MZN: "MT", NAD: "$", NGN: "₦", NIO: "C$", NOK: "kr", NPR: "₨",
  NZD: "NZ$", OMR: "ر.ع.", PAB: "B/.", PEN: "S/", PGK: "K", PHP: "₱", PKR: "₨", PLN: "zł", PYG: "₲",
  QAR: "ر.ق", RON: "lei", RSD: "дин", RUB: "₽", RWF: "FRw", SAR: "ر.س", SBD: "$", SCR: "₨", SDG: "ج.س.",
  SEK: "kr", SGD: "S$", SLE: "Le", SOS: "Sh", SRD: "$", SSP: "£", STN: "Db", SYP: "£", SZL: "E",
  THB: "฿", TJS: "SM", TMT: "m", TND: "د.ت", TOP: "T$", TRY: "₺", TTD: "TT$", TWD: "NT$", TZS: "TSh",
  UAH: "₴", UGX: "USh", USD: "$", UYU: "$", UZS: "so'm", VES: "Bs.S", VND: "₫", VUV: "Vt", WST: "WS$",
  XAF: "FCFA", XCD: "EC$", XOF: "CFA", XPF: "₣", YER: "﷼", ZAR: "R", ZMW: "ZK", ZWL: "$",
}

const COUNTRIES_DATA: Omit<Country, "flag" | "currencySymbol">[] = [
  { code: "AF", name: "Afghanistan", currency: "AFN", timezone: "Asia/Kabul" },
  { code: "AL", name: "Albania", currency: "ALL", timezone: "Europe/Tirane" },
  { code: "DZ", name: "Algeria", currency: "DZD", timezone: "Africa/Algiers" },
  { code: "AD", name: "Andorra", currency: "EUR", timezone: "Europe/Andorra" },
  { code: "AO", name: "Angola", currency: "AOA", timezone: "Africa/Luanda" },
  { code: "AG", name: "Antigua and Barbuda", currency: "XCD", timezone: "America/Antigua" },
  { code: "AR", name: "Argentina", currency: "ARS", timezone: "America/Argentina/Buenos_Aires" },
  { code: "AM", name: "Armenia", currency: "AMD", timezone: "Asia/Yerevan" },
  { code: "AU", name: "Australia", currency: "AUD", timezone: "Australia/Sydney" },
  { code: "AT", name: "Austria", currency: "EUR", timezone: "Europe/Vienna" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", timezone: "Asia/Baku" },
  { code: "BS", name: "Bahamas", currency: "BSD", timezone: "America/Nassau" },
  { code: "BH", name: "Bahrain", currency: "BHD", timezone: "Asia/Bahrain" },
  { code: "BD", name: "Bangladesh", currency: "BDT", timezone: "Asia/Dhaka" },
  { code: "BB", name: "Barbados", currency: "BBD", timezone: "America/Barbados" },
  { code: "BY", name: "Belarus", currency: "BYN", timezone: "Europe/Minsk" },
  { code: "BE", name: "Belgium", currency: "EUR", timezone: "Europe/Brussels" },
  { code: "BZ", name: "Belize", currency: "BZD", timezone: "America/Belize" },
  { code: "BJ", name: "Benin", currency: "XOF", timezone: "Africa/Porto-Novo" },
  { code: "BT", name: "Bhutan", currency: "BTN", timezone: "Asia/Thimphu" },
  { code: "BO", name: "Bolivia", currency: "BOB", timezone: "America/La_Paz" },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM", timezone: "Europe/Sarajevo" },
  { code: "BW", name: "Botswana", currency: "BWP", timezone: "Africa/Gaborone" },
  { code: "BR", name: "Brazil", currency: "BRL", timezone: "America/Sao_Paulo" },
  { code: "BN", name: "Brunei", currency: "BND", timezone: "Asia/Brunei" },
  { code: "BG", name: "Bulgaria", currency: "BGN", timezone: "Europe/Sofia" },
  { code: "BF", name: "Burkina Faso", currency: "XOF", timezone: "Africa/Ouagadougou" },
  { code: "BI", name: "Burundi", currency: "BIF", timezone: "Africa/Bujumbura" },
  { code: "CV", name: "Cabo Verde", currency: "CVE", timezone: "Atlantic/Cape_Verde" },
  { code: "KH", name: "Cambodia", currency: "KHR", timezone: "Asia/Phnom_Penh" },
  { code: "CM", name: "Cameroon", currency: "XAF", timezone: "Africa/Douala" },
  { code: "CA", name: "Canada", currency: "CAD", timezone: "America/Toronto" },
  { code: "CF", name: "Central African Republic", currency: "XAF", timezone: "Africa/Bangui" },
  { code: "TD", name: "Chad", currency: "XAF", timezone: "Africa/Ndjamena" },
  { code: "CL", name: "Chile", currency: "CLP", timezone: "America/Santiago" },
  { code: "CN", name: "China", currency: "CNY", timezone: "Asia/Shanghai" },
  { code: "CO", name: "Colombia", currency: "COP", timezone: "America/Bogota" },
  { code: "KM", name: "Comoros", currency: "KMF", timezone: "Indian/Comoro" },
  { code: "CG", name: "Congo", currency: "XAF", timezone: "Africa/Brazzaville" },
  { code: "CD", name: "Congo (Democratic Republic)", currency: "CDF", timezone: "Africa/Kinshasa" },
  { code: "CR", name: "Costa Rica", currency: "CRC", timezone: "America/Costa_Rica" },
  { code: "HR", name: "Croatia", currency: "EUR", timezone: "Europe/Zagreb" },
  { code: "CU", name: "Cuba", currency: "CUP", timezone: "America/Havana" },
  { code: "CY", name: "Cyprus", currency: "EUR", timezone: "Asia/Nicosia" },
  { code: "CZ", name: "Czech Republic", currency: "CZK", timezone: "Europe/Prague" },
  { code: "DK", name: "Denmark", currency: "DKK", timezone: "Europe/Copenhagen" },
  { code: "DJ", name: "Djibouti", currency: "DJF", timezone: "Africa/Djibouti" },
  { code: "DM", name: "Dominica", currency: "XCD", timezone: "America/Dominica" },
  { code: "DO", name: "Dominican Republic", currency: "DOP", timezone: "America/Santo_Domingo" },
  { code: "EC", name: "Ecuador", currency: "USD", timezone: "America/Guayaquil" },
  { code: "EG", name: "Egypt", currency: "EGP", timezone: "Africa/Cairo" },
  { code: "SV", name: "El Salvador", currency: "USD", timezone: "America/El_Salvador" },
  { code: "GQ", name: "Equatorial Guinea", currency: "XAF", timezone: "Africa/Malabo" },
  { code: "ER", name: "Eritrea", currency: "ERN", timezone: "Africa/Asmara" },
  { code: "EE", name: "Estonia", currency: "EUR", timezone: "Europe/Tallinn" },
  { code: "SZ", name: "Eswatini", currency: "SZL", timezone: "Africa/Mbabane" },
  { code: "ET", name: "Ethiopia", currency: "ETB", timezone: "Africa/Addis_Ababa" },
  { code: "FJ", name: "Fiji", currency: "FJD", timezone: "Pacific/Fiji" },
  { code: "FI", name: "Finland", currency: "EUR", timezone: "Europe/Helsinki" },
  { code: "FR", name: "France", currency: "EUR", timezone: "Europe/Paris" },
  { code: "GA", name: "Gabon", currency: "XAF", timezone: "Africa/Libreville" },
  { code: "GM", name: "Gambia", currency: "GMD", timezone: "Africa/Banjul" },
  { code: "GE", name: "Georgia", currency: "GEL", timezone: "Asia/Tbilisi" },
  { code: "DE", name: "Germany", currency: "EUR", timezone: "Europe/Berlin" },
  { code: "GH", name: "Ghana", currency: "GHS", timezone: "Africa/Accra" },
  { code: "GR", name: "Greece", currency: "EUR", timezone: "Europe/Athens" },
  { code: "GD", name: "Grenada", currency: "XCD", timezone: "America/Grenada" },
  { code: "GT", name: "Guatemala", currency: "GTQ", timezone: "America/Guatemala" },
  { code: "GN", name: "Guinea", currency: "GNF", timezone: "Africa/Conakry" },
  { code: "GW", name: "Guinea-Bissau", currency: "XOF", timezone: "Africa/Bissau" },
  { code: "GY", name: "Guyana", currency: "GYD", timezone: "America/Guyana" },
  { code: "HT", name: "Haiti", currency: "HTG", timezone: "America/Port-au-Prince" },
  { code: "HN", name: "Honduras", currency: "HNL", timezone: "America/Tegucigalpa" },
  { code: "HU", name: "Hungary", currency: "HUF", timezone: "Europe/Budapest" },
  { code: "IS", name: "Iceland", currency: "ISK", timezone: "Atlantic/Reykjavik" },
  { code: "IN", name: "India", currency: "INR", timezone: "Asia/Kolkata" },
  { code: "ID", name: "Indonesia", currency: "IDR", timezone: "Asia/Jakarta" },
  { code: "IR", name: "Iran", currency: "IRR", timezone: "Asia/Tehran" },
  { code: "IQ", name: "Iraq", currency: "IQD", timezone: "Asia/Baghdad" },
  { code: "IE", name: "Ireland", currency: "EUR", timezone: "Europe/Dublin" },
  { code: "IL", name: "Israel", currency: "ILS", timezone: "Asia/Jerusalem" },
  { code: "IT", name: "Italy", currency: "EUR", timezone: "Europe/Rome" },
  { code: "JM", name: "Jamaica", currency: "JMD", timezone: "America/Jamaica" },
  { code: "JP", name: "Japan", currency: "JPY", timezone: "Asia/Tokyo" },
  { code: "JO", name: "Jordan", currency: "JOD", timezone: "Asia/Amman" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", timezone: "Asia/Almaty" },
  { code: "KE", name: "Kenya", currency: "KES", timezone: "Africa/Nairobi" },
  { code: "KI", name: "Kiribati", currency: "AUD", timezone: "Pacific/Tarawa" },
  { code: "KP", name: "North Korea", currency: "KPW", timezone: "Asia/Pyongyang" },
  { code: "KR", name: "South Korea", currency: "KRW", timezone: "Asia/Seoul" },
  { code: "KW", name: "Kuwait", currency: "KWD", timezone: "Asia/Kuwait" },
  { code: "KG", name: "Kyrgyzstan", currency: "KGS", timezone: "Asia/Bishkek" },
  { code: "LA", name: "Laos", currency: "LAK", timezone: "Asia/Vientiane" },
  { code: "LV", name: "Latvia", currency: "EUR", timezone: "Europe/Riga" },
  { code: "LB", name: "Lebanon", currency: "LBP", timezone: "Asia/Beirut" },
  { code: "LS", name: "Lesotho", currency: "LSL", timezone: "Africa/Maseru" },
  { code: "LR", name: "Liberia", currency: "LRD", timezone: "Africa/Monrovia" },
  { code: "LY", name: "Libya", currency: "LYD", timezone: "Africa/Tripoli" },
  { code: "LI", name: "Liechtenstein", currency: "CHF", timezone: "Europe/Vaduz" },
  { code: "LT", name: "Lithuania", currency: "EUR", timezone: "Europe/Vilnius" },
  { code: "LU", name: "Luxembourg", currency: "EUR", timezone: "Europe/Luxembourg" },
  { code: "MG", name: "Madagascar", currency: "MGA", timezone: "Indian/Antananarivo" },
  { code: "MW", name: "Malawi", currency: "MWK", timezone: "Africa/Blantyre" },
  { code: "MY", name: "Malaysia", currency: "MYR", timezone: "Asia/Kuala_Lumpur" },
  { code: "MV", name: "Maldives", currency: "MVR", timezone: "Indian/Maldives" },
  { code: "ML", name: "Mali", currency: "XOF", timezone: "Africa/Bamako" },
  { code: "MT", name: "Malta", currency: "EUR", timezone: "Europe/Malta" },
  { code: "MH", name: "Marshall Islands", currency: "USD", timezone: "Pacific/Majuro" },
  { code: "MR", name: "Mauritania", currency: "MRU", timezone: "Africa/Nouakchott" },
  { code: "MU", name: "Mauritius", currency: "MUR", timezone: "Indian/Mauritius" },
  { code: "MX", name: "Mexico", currency: "MXN", timezone: "America/Mexico_City" },
  { code: "FM", name: "Micronesia", currency: "USD", timezone: "Pacific/Pohnpei" },
  { code: "MD", name: "Moldova", currency: "MDL", timezone: "Europe/Chisinau" },
  { code: "MC", name: "Monaco", currency: "EUR", timezone: "Europe/Monaco" },
  { code: "MN", name: "Mongolia", currency: "MNT", timezone: "Asia/Ulaanbaatar" },
  { code: "ME", name: "Montenegro", currency: "EUR", timezone: "Europe/Podgorica" },
  { code: "MA", name: "Morocco", currency: "MAD", timezone: "Africa/Casablanca" },
  { code: "MZ", name: "Mozambique", currency: "MZN", timezone: "Africa/Maputo" },
  { code: "MM", name: "Myanmar", currency: "MMK", timezone: "Asia/Yangon" },
  { code: "NA", name: "Namibia", currency: "NAD", timezone: "Africa/Windhoek" },
  { code: "NR", name: "Nauru", currency: "AUD", timezone: "Pacific/Nauru" },
  { code: "NP", name: "Nepal", currency: "NPR", timezone: "Asia/Kathmandu" },
  { code: "NL", name: "Netherlands", currency: "EUR", timezone: "Europe/Amsterdam" },
  { code: "NZ", name: "New Zealand", currency: "NZD", timezone: "Pacific/Auckland" },
  { code: "NI", name: "Nicaragua", currency: "NIO", timezone: "America/Managua" },
  { code: "NE", name: "Niger", currency: "XOF", timezone: "Africa/Niamey" },
  { code: "NG", name: "Nigeria", currency: "NGN", timezone: "Africa/Lagos" },
  { code: "MK", name: "North Macedonia", currency: "MKD", timezone: "Europe/Skopje" },
  { code: "NO", name: "Norway", currency: "NOK", timezone: "Europe/Oslo" },
  { code: "OM", name: "Oman", currency: "OMR", timezone: "Asia/Muscat" },
  { code: "PK", name: "Pakistan", currency: "PKR", timezone: "Asia/Karachi" },
  { code: "PW", name: "Palau", currency: "USD", timezone: "Pacific/Palau" },
  { code: "PS", name: "Palestine", currency: "ILS", timezone: "Asia/Gaza" },
  { code: "PA", name: "Panama", currency: "PAB", timezone: "America/Panama" },
  { code: "PG", name: "Papua New Guinea", currency: "PGK", timezone: "Pacific/Port_Moresby" },
  { code: "PY", name: "Paraguay", currency: "PYG", timezone: "America/Asuncion" },
  { code: "PE", name: "Peru", currency: "PEN", timezone: "America/Lima" },
  { code: "PH", name: "Philippines", currency: "PHP", timezone: "Asia/Manila" },
  { code: "PL", name: "Poland", currency: "PLN", timezone: "Europe/Warsaw" },
  { code: "PT", name: "Portugal", currency: "EUR", timezone: "Europe/Lisbon" },
  { code: "QA", name: "Qatar", currency: "QAR", timezone: "Asia/Qatar" },
  { code: "RO", name: "Romania", currency: "RON", timezone: "Europe/Bucharest" },
  { code: "RU", name: "Russia", currency: "RUB", timezone: "Europe/Moscow" },
  { code: "RW", name: "Rwanda", currency: "RWF", timezone: "Africa/Kigali" },
  { code: "KN", name: "Saint Kitts and Nevis", currency: "XCD", timezone: "America/St_Kitts" },
  { code: "LC", name: "Saint Lucia", currency: "XCD", timezone: "America/St_Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines", currency: "XCD", timezone: "America/St_Vincent" },
  { code: "WS", name: "Samoa", currency: "WST", timezone: "Pacific/Apia" },
  { code: "SM", name: "San Marino", currency: "EUR", timezone: "Europe/San_Marino" },
  { code: "ST", name: "Sao Tome and Principe", currency: "STN", timezone: "Africa/Sao_Tome" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", timezone: "Asia/Riyadh" },
  { code: "SN", name: "Senegal", currency: "XOF", timezone: "Africa/Dakar" },
  { code: "RS", name: "Serbia", currency: "RSD", timezone: "Europe/Belgrade" },
  { code: "SC", name: "Seychelles", currency: "SCR", timezone: "Indian/Mahe" },
  { code: "SL", name: "Sierra Leone", currency: "SLE", timezone: "Africa/Freetown" },
  { code: "SG", name: "Singapore", currency: "SGD", timezone: "Asia/Singapore" },
  { code: "SK", name: "Slovakia", currency: "EUR", timezone: "Europe/Bratislava" },
  { code: "SI", name: "Slovenia", currency: "EUR", timezone: "Europe/Ljubljana" },
  { code: "SB", name: "Solomon Islands", currency: "SBD", timezone: "Pacific/Guadalcanal" },
  { code: "SO", name: "Somalia", currency: "SOS", timezone: "Africa/Mogadishu" },
  { code: "ZA", name: "South Africa", currency: "ZAR", timezone: "Africa/Johannesburg" },
  { code: "SS", name: "South Sudan", currency: "SSP", timezone: "Africa/Juba" },
  { code: "ES", name: "Spain", currency: "EUR", timezone: "Europe/Madrid" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", timezone: "Asia/Colombo" },
  { code: "SD", name: "Sudan", currency: "SDG", timezone: "Africa/Khartoum" },
  { code: "SR", name: "Suriname", currency: "SRD", timezone: "America/Paramaribo" },
  { code: "SE", name: "Sweden", currency: "SEK", timezone: "Europe/Stockholm" },
  { code: "CH", name: "Switzerland", currency: "CHF", timezone: "Europe/Zurich" },
  { code: "SY", name: "Syria", currency: "SYP", timezone: "Asia/Damascus" },
  { code: "TW", name: "Taiwan", currency: "TWD", timezone: "Asia/Taipei" },
  { code: "TJ", name: "Tajikistan", currency: "TJS", timezone: "Asia/Dushanbe" },
  { code: "TZ", name: "Tanzania", currency: "TZS", timezone: "Africa/Dar_es_Salaam" },
  { code: "TH", name: "Thailand", currency: "THB", timezone: "Asia/Bangkok" },
  { code: "TL", name: "Timor-Leste", currency: "USD", timezone: "Asia/Dili" },
  { code: "TG", name: "Togo", currency: "XOF", timezone: "Africa/Lome" },
  { code: "TO", name: "Tonga", currency: "TOP", timezone: "Pacific/Tongatapu" },
  { code: "TT", name: "Trinidad and Tobago", currency: "TTD", timezone: "America/Port_of_Spain" },
  { code: "TN", name: "Tunisia", currency: "TND", timezone: "Africa/Tunis" },
  { code: "TR", name: "Turkey", currency: "TRY", timezone: "Europe/Istanbul" },
  { code: "TM", name: "Turkmenistan", currency: "TMT", timezone: "Asia/Ashgabat" },
  { code: "TV", name: "Tuvalu", currency: "AUD", timezone: "Pacific/Funafuti" },
  { code: "UG", name: "Uganda", currency: "UGX", timezone: "Africa/Kampala" },
  { code: "UA", name: "Ukraine", currency: "UAH", timezone: "Europe/Kyiv" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", timezone: "Asia/Dubai" },
  { code: "GB", name: "United Kingdom", currency: "GBP", timezone: "Europe/London" },
  { code: "US", name: "United States", currency: "USD", timezone: "America/New_York" },
  { code: "UY", name: "Uruguay", currency: "UYU", timezone: "America/Montevideo" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", timezone: "Asia/Tashkent" },
  { code: "VU", name: "Vanuatu", currency: "VUV", timezone: "Pacific/Efate" },
  { code: "VA", name: "Vatican City", currency: "EUR", timezone: "Europe/Vatican" },
  { code: "VE", name: "Venezuela", currency: "VES", timezone: "America/Caracas" },
  { code: "VN", name: "Vietnam", currency: "VND", timezone: "Asia/Ho_Chi_Minh" },
  { code: "YE", name: "Yemen", currency: "YER", timezone: "Asia/Aden" },
  { code: "ZM", name: "Zambia", currency: "ZMW", timezone: "Africa/Lusaka" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWL", timezone: "Africa/Harare" },
]

export const COUNTRIES: Country[] = COUNTRIES_DATA.map((c) => ({
  ...c,
  flag: getFlagEmoji(c.code),
  currencySymbol: CURRENCY_SYMBOLS[c.currency] ?? c.currency,
}))
